# -*- mode: ruby -*-


###
# Vagrant Configuration
#
Vagrant.configure("2") do |config|

  # Base Box
  # --------------------
  config.vm.box = "chef/debian-7.7"

  # IP of the box
  # Note: Use an IP that doesn't conflict with any OS's DHCP
  # --------------------
  #config.vm.network "private_network", ip: "192.168.33.164"

  # Synced Folders
  # Note: Requires nfsd package to be installed (except windows, nfs mount option will be irgnored on windows host)!
  # --------------------
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"

  # Box performance settings (virtualbox-provider only!)
  # --------------------
  config.vm.provider "virtualbox" do |v|
    #v.memory = 1024
    #v.cpus = 2

    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Disable auto checking and updating correct guest additions version when booting the machine
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  # Provisioning
  # --------------------
  config.vm.provision "shell", path: "/vagrant/test/run.sh",

end
